### ISSUE TITLE
使用最新源码报错

### ISSUE THREAD

**Issue by SouHong** [paldier/K3-merlin#3]
感谢分享源码
使用最新源码编译报错如下:
make[5]: 进入目录“/home/zs/k3-merlin/release/src/router/libev-4.22”
/bin/bash ./libtool  --tag=CC   --mode=link arm-brcm-linux-uclibcgnueabi-gcc  -DBCMWPA2 -DBCMQOS -DEXT_ACS -DD11AC_IOTYPES -DPHYMON -DPROXYARP -DTRAFFIC_MGMT -DTRAFFIC_MGMT_RSSI_POLICY -DMFP -D__CONFIG_MFP__ -DLINUX26 -DCONFIG_BCMWL5 -DDEBUG_NOISY -DDEBUG_RCTEST -pipe -DBCMWPA2 -DBCMARM -fno-strict-aliasing -marm -DLINUX_KERNEL_VERSION=132644  -DRTAC3100 -O2 -D__CONFIG_DHDAP__ -D__CONFIG_GMAC3__ -DBCM_BSD -DBCM_DCS -D__CONFIG_EMF__ -D__CONFIG_WPS__ -version-info 4:0:0  -o libev.la -rpath /usr/lib ev.lo event.lo  -lm 
libtool: link: arm-brcm-linux-uclibcgnueabi-gcc -shared  -fPIC -DPIC  .libs/ev.o .libs/event.o   -lm  -marm -O2   -Wl,-soname -Wl,libev.so.4 -o .libs/libev.so.4.0.0
arm-brcm-linux-uclibcgnueabi-gcc: .libs/ev.o: No such file or directory
arm-brcm-linux-uclibcgnueabi-gcc: .libs/event.o: No such file or directory
Makefile:441: recipe for target 'libev.la' failed
make[5]: *** [libev.la] Error 1
make[5]: 离开目录“/home/zs/k3-merlin/release/src/router/libev-4.22”
Makefile:351: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: 离开目录“/home/zs/k3-merlin/release/src/router/libev-4.22”
Makefile:1996: recipe for target 'libev-4.22' failed
make[3]: *** [libev-4.22] Error 2
make[3]: 离开目录“/home/zs/k3-merlin/release/src/router”
Makefile:202: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: 离开目录“/home/zs/k3-merlin/release/src-rt-7.14.114.x/src”
Makefile:2826: recipe for target 'bin' failed

**Comment by paldier** [comment]
感觉makefile配置的一直有问题，手动删除吧

**Comment by SouHong** [comment]
makefile配置已经没有问题了。需要添加几个文件或文件夹就可以正常编译。
