### ISSUE TITLE
有办法精简固件大小吗？30M以内

### ISSUE THREAD

**Issue by geoleonsh** [paldier/K3-merlin#4]
有啥办法精简大小吗？我只保留了中文语言，但是收效甚微，固件大了些，但是是按默认配置编译的

**Comment by paldier** [comment]
jffs定死的90m精简有何意义

**Comment by geoleonsh** [comment]
是的，另外还有一个问题，router模式下的wan和lan顺序怎么改？cfe中改了不行，init.rc中加了个nvram set wanports也不行，是加错位置了还是啥，麻烦指导一下
